<?php

/**
 * @file
 * Code for the Visualization Entity Charts feature.
 */

include_once 'visualization_entity_charts.features.inc';

/**
 * Implements hook_form_alter().
 */
function visualization_entity_charts_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'eck__entity__form_add_visualization_ve_chart':
    case 'eck__entity__form_edit_visualization_ve_chart':
      $form['#attached']['libraries_load'][] = array('recline');
      $form['#attached']['libraries_load'][] = array('d3');
      $form['#attached']['libraries_load'][] = array('nvd3');
      $form['#attached']['libraries_load'][] = array('reclineViewNvd3');
      $form['#attached']['libraries_load'][] = array('csv');
      $form['#attached']['libraries_load'][] = array('mustache');
      $form['#attached']['libraries_load'][] = array('lodash');
      $form['#attached']['libraries_load'][] = array('lodash_data');
      $form['#attached']['libraries_load'][] = array('moment');
      $form['#attached']['libraries_load'][] = array('slickgrid');
      $form['#attached']['libraries_load'][] = array('chosen_bootstrap');

      $form['#attached']['css'][] = drupal_get_path('module', 'visualization_entity_charts') . '/ve_chart.css';
      drupal_add_js(drupal_get_path('module', 'visualization_entity_charts') . '/visualization_entity_charts.js', array('weight' => 100));
      break;

  }
}
/**
 * Implements hook_entity_view().
 */
function visualization_entity_charts_entity_view($entity, $type, $view_mode, $langcode) {
  if ($type == 'visualization' && $entity->type == 've_chart') {
    $entity->content['#suffix'] = '<div id="graph"></div>';
    libraries_load('recline');
    libraries_load('d3');
    libraries_load('nvd3');
    libraries_load('reclineViewNvd3');
    libraries_load('csv');
    libraries_load('mustache');
    libraries_load('lodash');
    libraries_load('lodash_data');
    libraries_load('chosen');
    libraries_load('moment');
    libraries_load('slickgrid');
    libraries_load('chosen_bootstrap');

    $entity->content['#attached']['css'][] = drupal_get_path('module', 'visualization_entity_charts') . '/ve_chart.css';
    drupal_add_js(drupal_get_path('module', 'visualization_entity_charts') . '/visualization_entity_charts_view.js', array('weight' => 100));
  }
}
/**
 * Implements hook_theme().
 */
function visualization_entity_charts_theme($existing, $type, $theme, $path) {
  return array(
    'eck__entity__form_add_visualization_ve_chart' => array(
      'render element' => 'form',
      'template' => 've-chart-form',
      'path' => drupal_get_path('module', 'visualization_entity_charts'),
    ),
    'eck__entity__form_edit_visualization_ve_chart' => array(
      'render element' => 'form',
      'template' => 've-chart-form',
      'path' => drupal_get_path('module', 'visualization_entity_charts'),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function visualization_entity_charts_libraries_info() {
  $libraries = array();
  $libraries['nvd3'] = array(
    'name' => 'NVD3',
    'vendor url' => 'https://github.com/novus/nvd3',
    'download url' => 'https://github.com/novus/nvd3/archive/master.zip',
    'path' => '',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'dependencies' => array('d3'),
    'files' => array(
      'js' => array(
        'build/nv.d3.min.js',
      ),
      'css' => array(
        'build/nv.d3.min.css',
      ),
    ),
  );
  $libraries['d3'] = array(
    'name' => 'D3',
    'vendor url' => 'https://github.com/mbostock/d3',
    'download url' => 'https://github.com/mbostock/d3/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'd3.min.js',
      ),
    ),
  );
  $libraries['reclineViewNvd3'] = array(
    'name' => 'recline.view.nvd3.js',
    'vendor url' => 'https://github.com/NuCivic/recline.view.nvd3.js',
    'download url' => 'https://github.com/NuCivic/recline.view.nvd3.js/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'dist/recline.view.nvd3.min.js',
      ),
      'css' => array(
        'css/style.css',
      ),
    ),
  );

  $libraries['recline'] = array(
    'name' => 'recline',
    'vendor url' => 'https://github.com/okfn/recline',
    'download url' => 'https://github.com/okfn/recline/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'dist/recline.js',
        'dist/recline.dataset.js',
      ),
      'css' => (
        'dist/recline.css'
      )
    ),
  );

  $libraries['lodash'] = array(
    'name' => 'lodash',
    'vendor url' => 'https://github.com/lodash/lodash',
    'download url' => 'https://github.com/lodash/lodash/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'dist/lodash.compat.min.js',
      ),
    ),
  );

  $libraries['lodash_data'] = array(
    'name' => 'lodashdata',
    'vendor url' => 'https://github.com/NuCivic/lodash.data',
    'download url' => 'https://github.com/NuCivic/lodash.data/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'dist/lodash.data.min.js',
      ),
    ),
  );

  $libraries['slickgrid'] = array(
    'name' => 'SlickGrid',
    'vendor url' => 'https://github.com/mleibman/SlickGrid',
    'download url' => 'https://github.com/mleibman/SlickGrid/archive/master.zip',
    'version arguments' => array(
      'file' => 'slick.grid.js',
      'pattern' => '/SlickGrid v(\d+\.\d+)/',
    ),
    'files' => array(
      'js' => array(
        'slick.core.js',
        'slick.formatters.js',
        'slick.editors.js',
        'slick.grid.js',
        'lib/jquery-ui-1.8.16.custom.min.js',
        'lib/jquery.event.drag-2.2.js',
        'lib/jquery.event.drop-2.2.js',
        'plugins/slick.rowselectionmodel.js',
        'plugins/slick.rowmovemanager.js',
      ),
      'css' => array(
        'slick.grid.css'
      ),
    ),
  );

  $libraries['moment'] = array(
    'name' => 'moment',
    'vendor url' => 'https://github.com/moment/moment',
    'download url' => 'https://github.com/moment/moment/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'min/moment.min.js',
      ),
    ),
  );

  $libraries['mustache'] = array(
    'name' => 'mustache',
    'vendor url' => 'http://github.com/janl/mustache.js',
    'download url' => 'http://github.com/janl/mustache.js.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'mustache.min.js',
      ),
    ),
  );

  $libraries['chosen'] = array(
    'name' => 'chosen',
    'vendor url' => 'https://github.com/harvesthq/chosen',
    'download url' => 'https://github.com/harvesthq/chosen/releases/download/v1.3.0/chosen_v1.3.0.zip',
    'version arguments' => array(
      'file' => 'chosen.jquery.min.js',
      'pattern' => '/Chosen v(\d+\.\d+\.\d+)/',
    ),
    'files' => array(
      'js' => array(
        'chosen.jquery.min.js',
      ),
    ),
  );

  $libraries['chosen_bootstrap'] = array(
    'name' => 'chosen_bootstrap',
    'vendor url' => 'https://github.com/dbtek/chosen-bootstrap',
    'download url' => 'https://github.com/dbtek/chosen-bootstrap.git',
    'version arguments' => array(
      'file' => 'bower.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'css' => array(
        'chosen.bootstrap.min.css',
      ),
    ),
  );

  $libraries['csv'] = array(
    'name' => 'csv',
    'vendor url' => 'https://github.com/okfn/csv.js',
    'version' => '0.0.1',
    'files' => array(
      'js' => array(
        'csv.js',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_block_info().
 */
function visualization_entity_charts_block_info() {
  $blocks = array();
  $blocks['ve_chart_button'] = array(
    'info' => t('Viz Entity Chart Button'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_libraries_info_alter().
 */
function visualization_entity_charts_libraries_info_alter(&$libraries) {
  if (isset($libraries['recline']['files']['js'])) {
    $recline = $libraries['recline']['files']['js'];
    $index = array_search('vendor/timeline/js/timeline.js', $recline);
    unset($libraries['recline']['files']['js'][$index]);
  }
}

/**
 * Preprocess for chart add form.
 */
function template_preprocess_eck__entity__form_add_visualization_ve_chart(&$vars) {
  template_preprocess_eck__entity__form_edit_visualization_ve_chart($vars);
}

/**
 * Preprocess for chart edit form.
 */
function template_preprocess_eck__entity__form_edit_visualization_ve_chart(&$vars) {
  $form = $vars['form'];
  $vars['save'] = $form['actions'];
  $vars['title'] = $form['title'];
  $vars['settings'] = $form['field_ve_settings'];
  unset($vars['form']['title']);
  unset($vars['form']['field_ve_settings']);
  unset($vars['form']['actions']);
  $available_fields = field_info_instances('visualization', 've_chart');
  unset($available_fields['field_ve_settings']);
  $fields = array();
  $vars['fields'] = array();
  foreach ($available_fields as $field => $instance) {
    $fields[$field] = $form[$field]['#weight'];
  }
  asort($fields);
  foreach ($fields as $field => $weight) {
    $vars['fields'][$field] = $form[$field];
    unset($vars['form'][$field]);
  }
}
