<?php
/**
 * @file
 * visualization_entity_charts.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function visualization_entity_charts_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'visualization-ve_chart-field_ve_group'
  $field_instances['visualization-ve_chart-field_ve_group'] = array(
    'bundle' => 've_chart',
    'default_value' => array(
      0 => array(
        'value' => 0,
      ),
    ),
    'deleted' => 0,
    'description' => 'Decide whether or not to group common values for the Series Fields.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 8,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'visualization',
    'field_name' => 'field_ve_group',
    'label' => 'Group',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 7,
    ),
  );

  // Exported field_instance: 'visualization-ve_chart-field_ve_height'
  $field_instances['visualization-ve_chart-field_ve_height'] = array(
    'bundle' => 've_chart',
    'default_value' => array(
      0 => array(
        'value' => 500,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 10,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'visualization',
    'field_name' => 'field_ve_height',
    'label' => 'Height',
    'required' => 0,
    'settings' => array(
      'max' => 9999,
      'min' => 50,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 9,
    ),
  );

  // Exported field_instance: 'visualization-ve_chart-field_ve_series_fields'
  $field_instances['visualization-ve_chart-field_ve_series_fields'] = array(
    'bundle' => 've_chart',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Data that will appear as the Y-Axis variables. Separate multiple fields with commas.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 7,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'visualization',
    'field_name' => 'field_ve_series_fields',
    'label' => 'Series Fields',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'visualization-ve_chart-field_ve_type'
  $field_instances['visualization-ve_chart-field_ve_type'] = array(
    'bundle' => 've_chart',
    'default_value' => array(
      0 => array(
        'value' => 'discreteBarChart',
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'visualization',
    'field_name' => 'field_ve_type',
    'label' => 'Type',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'apply_chosen' => 0,
      ),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'visualization-ve_chart-field_ve_width'
  $field_instances['visualization-ve_chart-field_ve_width'] = array(
    'bundle' => 've_chart',
    'default_value' => array(
      0 => array(
        'value' => 500,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 9,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'visualization',
    'field_name' => 'field_ve_width',
    'label' => 'Width',
    'required' => 0,
    'settings' => array(
      'max' => 9999,
      'min' => 50,
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 8,
    ),
  );

  // Exported field_instance: 'visualization-ve_chart-field_ve_x_field'
  $field_instances['visualization-ve_chart-field_ve_x_field'] = array(
    'bundle' => 've_chart',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Data that will be on the bottom or X-Axis of the graph.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 6,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'visualization',
    'field_name' => 'field_ve_x_field',
    'label' => 'X-Field',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 40,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Data that will appear as the Y-Axis variables. Separate multiple fields with commas.');
  t('Data that will be on the bottom or X-Axis of the graph.');
  t('Decide whether or not to group common values for the Series Fields.');
  t('Group');
  t('Height');
  t('Series Fields');
  t('Type');
  t('Width');
  t('X-Field');

  return $field_instances;
}
