<?php

/**
 * @file
 * Code for the Visualization Entity Charts feature.
 */

include_once 'visualization_entity_charts.features.inc';

/**
 * Implements hook_menu().
 */
function visualization_entity_charts_menu() {
  $items = array();

  $items['resource_by_nid/%'] = array(
    'title' => 'Resource by NID',
    'page callback' => 'visualization_entity_charts_resource_by_nid',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

/**
 * Returns resource given nid.
 */
function visualization_entity_charts_resource_by_nid($nid) {
  if ($cache = cache_get('resource_by_nid_' . $nid)) {
    drupal_json_output($cache->data);
  }
  else {
    $node = node_load($nid);
    if ($file = dkan_datastore_file_field($node)) {
      $status = dkan_datastore_status($node);
      if ($status == DKAN_DATASTORE_EXISTS) {
        $output = array(
          'type' => 'api',
          'url' => '/api/action/datastore/search.json?resource_id=' . $node->uuid,
          'uuid' => $node->uuid,
        );
      }
      else {
        $output = array(
          'type' => 'file',
          'url' => file_create_url($file->uri),
        );
      }
      cache_set('resource_by_nid_' . $nid, $output, 'cache');
      return drupal_json_output($output);
    }
    return drupal_json_output(array());
  }
}


/**
 * Implements hook_form_alter().
 */
function visualization_entity_charts_form_alter(&$form, $form_state, $form_id) {
  switch ($form_id) {
    case 'eck__entity__form_add_visualization_ve_chart':
    case 'eck__entity__form_edit_visualization_ve_chart':
      $form['#attached']['css'][] = drupal_get_path('module', 'visualization_entity_charts') . '/ve_chart.css';
      $form['#attached']['js'][] = drupal_get_path('module', 'visualization_entity_charts') . '/visualization_entity_charts.js';
      $form['#attached']['libraries_load'][] = array('recline');
      $form['#attached']['libraries_load'][] = array('d3');
      $form['#attached']['libraries_load'][] = array('nvd3');
      $form['#attached']['libraries_load'][] = array('recline.view.nvd3.js');
      break;

  }
}

/**
 * Implements hook_theme().
 */
function visualization_entity_charts_theme($existing, $type, $theme, $path) {
  return array(
    'eck__entity__form_add_visualization_ve_chart' => array(
      'render element' => 'form',
      'template' => 've-chart-form',
      'path' => drupal_get_path('module', 'visualization_entity_charts'),
    ),
    'eck__entity__form_edit_visualization_ve_chart' => array(
      'render element' => 'form',
      'template' => 've-chart-form',
      'path' => drupal_get_path('module', 'visualization_entity_charts'),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function visualization_entity_charts_libraries_info() {
  $libraries = array();
  $libraries['nvd3'] = array(
    'name' => 'NVD3',
    'vendor url' => 'https://github.com/novus/nvd3',
    'download url' => 'https://github.com/novus/nvd3/archive/master.zip',
    'path' => '',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'nv.d3.min.js',
      ),
      'css' => array(
        'nv.d3.min.css',
      ),
    ),
  );
  $libraries['d3'] = array(
    'name' => 'D3',
    'vendor url' => 'https://github.com/mbostock/d3',
    'download url' => 'https://github.com/mbostock/d3/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'd3.min.js',
      ),
    ),
  );
  $libraries['recline.view.nvd3.js'] = array(
    'name' => 'recline.view.nvd3.js',
    'vendor url' => 'https://github.com/NuCivic/recline.view.nvd3.js',
    'download url' => 'https://github.com/NuCivic/recline.view.nvd3.js/archive/master.zip',
    'version arguments' => array(
      'file' => 'package.json',
      'pattern' => '/"version": "(\d+\.\d+\.\d+)"/',
    ),
    'files' => array(
      'js' => array(
        'src/recline.view.nvd3.js',
      ),
    ),
  );
  return $libraries;
}
